### ISSUE TITLE
Announcement: @fmauchle is taking over as maintainer

### ISSUE THREAD

**Issue by fmauchle** [radsecproxy/radsecproxy#1]
For many years now, Linus Nordberg (@ln5) has maintained radsecproxy. He finally announced he would like to hand over this task now. Many thanks to Linus, and to all contributors for your efforts in all those years.

## New maintainer
@fmauchle will be taking responsibility as maintainer and further develop radsecproxy.

## New home
To relieve Linus from his duties, radsecproxy has moved to a new home on github, and a new website [radsecproxy.github.io](https://radsecproxy.github.io)

**Comment by ln5** [comment]
Thanks for taking this on, Fabian!

**Comment by paravoid** [comment]
Note that https://software.nordu.net/radsecproxy/ still exists, still points to the ol dgit repository and still claims the last version is 1.6.9, so it can be misleading to users not familiar with this transition.

**Comment by fmauchle** [comment]
> Note that https://software.nordu.net/radsecproxy/ still exists, still points to the ol dgit repository and still claims the last version is 1.6.9, so it can be misleading to users not familiar with this transition.

Thanks for the hint. Fixed. (redirecting to radsecproxy.github.io)

**Comment by paravoid** [comment]
https://software.nordu.net/ seems to be gone now, I guess that's OK :) Should this issue be closed now?
