### ISSUE TITLE
radsecproxy crash

### ISSUE THREAD

**Issue by rasheedi99** [radsecproxy/radsecproxy#109]
Dears,

I noticed suddenly that the radsecproxy service stopes, when I check the logs I found the below, anybody knows why and how to solve it? 

Dec  7 23:23:22 eduroam2 kernel: radsecproxy[31296]: segfault at 40 ip 0000000000409764 sp 00007f5e4ed1ad90 error 4 in radsecproxy[400000+23000]
Dec  7 23:23:25 eduroam2 abrt-hook-ccpp: Process 31268 (radsecproxy) of user 0 killed by SIGSEGV - dumping core
Dec  7 23:23:27 eduroam2 systemd: radsecproxy.service: main process exited, code=killed, status=11/SEGV
Dec  7 23:23:27 eduroam2 systemd: Unit radsecproxy.service entered failed state.
Dec  7 23:23:27 eduroam2 systemd: radsecproxy.service failed.
Dec  7 23:23:32 eduroam2 abrt-server: Executable '/usr/local/sbin/radsecproxy' doesn't belong to any package and ProcessUnpackaged is set to 'no'
Dec  7 23:23:32 eduroam2 abrt-server: 'post-create' on '/var/spool/abrt/ccpp-2022-12-07-23:23:25-31268' exited with 1
Dec  7 23:23:32 eduroam2 abrt-server: Deleting problem directory '/var/spool/abrt/ccpp-2022-12-07-23:23:25-31268'

**Comment by akchoubey** [comment]
Can you please share the configuration/steps to reproduce the crash ?

**Comment by rasheedi99** [comment]
the configuration is based on https://wiki.geant.org/display/H2eduroam/radsecproxy-flr 
it was working correctly for several years, but the issue coming now.

**Comment by rasheedi99** [comment]
The service stopped again yesterday with the same error. I have to restart it again every time 

Dec 12 18:50:07 eduroam2 kernel: radsecproxy[18028]: segfault at 40 ip 0000000000409764 sp 00007f919009dd90 error 4 in radsecproxy[400000+23000]
Dec 12 18:50:07 eduroam2 abrt-hook-ccpp: Process 18000 (radsecproxy) of user 0 killed by SIGSEGV - dumping core
Dec 12 18:50:07 eduroam2 systemd: radsecproxy.service: main process exited, code=killed, status=11/SEGV
Dec 12 18:50:07 eduroam2 systemd: Unit radsecproxy.service entered failed state.
Dec 12 18:50:07 eduroam2 systemd: radsecproxy.service failed.
Dec 12 18:50:07 eduroam2 abrt-server: Executable '/usr/local/sbin/radsecproxy' doesn't belong to any package and ProcessUnpackaged is set to 'no'
Dec 12 18:50:07 eduroam2 abrt-server: 'post-create' on '/var/spool/abrt/ccpp-2022-12-12-18:50:07-18000' exited with 1
Dec 12 18:50:07 eduroam2 abrt-server: Deleting problem directory '/var/spool/abrt/ccpp-2022-12-12-18:50:07-18000'

**Comment by akc5** [comment]
These logs are not that helpful. Can you take a core dump and run it through gdb and paste the stack trace here ? You might need to re-compile radsecproxy with '-g' if it hasn't been already. 
1. Also try running a different radsecproxy instance with different (simpler/minimal) configuration and observer the behavior.
2. If nothing has changed in a long time as you say then its worth checking the system state like memory, certs or any other dependencies that radsecproxy might have.

BTW, I've used radsecproxy recently to enable RadSec on our devices. It seems to work fine, so far ;)
