### ISSUE TITLE
manpage for radsecproxy.conf is not installed

### ISSUE THREAD

**Issue by hagedose** [radsecproxy/radsecproxy#11]
Version 1.7.1 does not install a manpage for radsecproxy.conf - is that intentional?

**Comment by fmauchle** [comment]
No, it should be installed.
Do you have a docbook2x compiler installed? (maybe its only installed if it was built)

**Comment by hagedose** [comment]
I didn't have it installed, but even when I install it, configure does not find it:

checking for docbook2x-man... no

I see that I can set the environment variable DOCBOOK2X_MAN, but I'm not sure what I should set it to. I installed the RPM named docbook2X-0.8.8-1.el6.x86_64

**Comment by fmauchle** [comment]
for RedHat I use package `docbook2X` and configure with `DOCBOOK2X_MAN=db2x_docbook2man`

**Comment by hagedose** [comment]
Thanks, that did the trick!
