### ISSUE TITLE
Sign releases

### ISSUE THREAD

**Issue by egroeper** [radsecproxy/radsecproxy#12]
Hi Fabian,

as this is a security software I really liked, that Linus signed the releases with his GPG key.
Please consider doing this, too.

Kind Regards,
Enno

**Comment by paravoid** [comment]
In Debian, we've been using the .asc file to check the authenticity of those releases and ship that .asc file in the archive as well. +1, would love to see this too.

**Comment by fmauchle** [comment]
Ok, let's do that - please educate me if I missed something or did it wrong...
I've created and uploaded the signature for the release tarball.
I guess post-signing the git tag isn't possible, so that will have to wait for the next release.

**Comment by paravoid** [comment]
This seems OK, but your key (`7CD43F7B83809D53BAAD691E3283E61E4EABD370`) seems to be a 1024 bits DSA key, which is _very_ weak and has been considered cryptographically obsolete for a while now. Your key is also using SHA1 as the digest algorithm which is also considered cryptographically broken. So you should generate a new e.g. RSA 4096 bits key with a recent version of gpg (newer versions have sane defaults).

Also, it would be great to establish some trust to this new key. I noticed your old key is not very well-connected to the WoT, and I suspect it'd be hard for you to get a lot of signatures for your new key as well. It might be worth it to at least ship an export of this key of yours (`gpg --armor --export-options export-minimal $KEYID`) in the project's homepage. (That may be a not very strong assertion, however, if e.g. only a username/password is required to update that website).

**Comment by paravoid** [comment]
Ping! I noticed the 1.7.2-rc1 release isn't signed :)

**Comment by fmauchle** [comment]
My apologies. I got stuck, (then distracted ;) ) exporting and publishing the new key. Should be all done now.
Just remembered that I could (should?) also sign the git tag, but it seems impossible to ammend a signature.

**Comment by egroeper** [comment]
Thank a lot for your effort! The tag for 1.7.2 is signed. Looks good.

One thing left: For the signature still the old key got used. Could you please change this to your new key for the next release?

**Comment by fmauchle** [comment]
True, and very strange (thanks for the heads up!)
Despite having configured git with the user.signingkey option, it picked the wrong key...

**Comment by paravoid** [comment]
I think this is now fixed, right?
