### ISSUE TITLE
Segfault crashes

### ISSUE THREAD

**Issue by mplaats** [radsecproxy/radsecproxy#129]
Hi,

We experiencing segfault crashes. Environment is debian 11 and version 1.8 segfaulted with an application crash. Version 1.9 from backports now running segfaults, but the application stays online.

[Wed Jun  7 14:15:17 2023 < 5278.569049>] radsecproxy[922004]: segfault at 40 ip 0000555aa987c8c0 sp 00007efd84afbe60 error 4 in radsecproxy[555aa9876000+18000]
[Wed Jun  7 14:15:17 2023 <    0.000023>] Code: 4c 24 0f 48 2b 95 88 00 00 00 48 39 f2 ba 01 00 00 00 0f 4f ca 88 4c 24 0f e9 e5 fe ff ff 0f 1f 40 00 49 8b 76 08 31 c0 31 ff <48> 8b 56 40 80 3a 0c 0f 85 e2 fe ff ff e9 f1 fe ff ff 66 0f 1f 44

Can you take a look at this behaviour ?

**Comment by fmauchle** [comment]
Could you specify the exact radsecproxy version you are running? `radsecporxy -v`

I presume this happens repeatedly. Could you collect a core dump?

**Comment by Popyllol** [comment]
Maybe DOS linefeeds in certificate? I had a similar issue with freeradius connected to an radsec that has a certificate with DOS linefeeds (^M).
