### ISSUE TITLE
1.7.1 release tarball's oddities

### ISSUE THREAD

**Issue by paravoid** [radsecproxy/radsecproxy#13]
The release tarball for 1.7.1, i.e. radsecproxy-1.7.1.tar.gz, contains all files as executable (+x).

I checked the GitHub-generated tarball (1.7.1.tar.gz) and it doesn't, however... there also seem to be random differences between the two, including e.g. whitespaces diffs in the ChangeLog.

**Comment by fmauchle** [comment]
Thanks for reporting.
Regenerated and re-uploaded the release tarball.
Should be fixed now. Please verify.

**Comment by fmauchle** [comment]
> There are differences between tarbal 1.7.1 and zip downloaded from master branch. In .zip version is missing file configure and some others

Yes, that's expected. The release tarball is provided for convenience so you don't have to have Autotools installed to build radsecproxy. And a few files meant for developers are also not included.
