### ISSUE TITLE
radsecproxy 1.8.1: Server is not accepting ciphers with ECDHE and DHE

### ISSUE THREAD

**Issue by chaitus84** [radsecproxy/radsecproxy#136]
I am using a radsec client to establish a connection with the radsecproxy server. I am using the 1.8.1 version. 

Connection is not successful when I enforce following ciphers in the client.

    "DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:"
    "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:"
    "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384"

When I add a non-DHE or non-ECDHE cipher to the client's supported list of ciphers, the connection is successful. 

Please let me know if there are any changes needed to the radsecproxy server to make it operate with ECDHE and DHE cipher suites. 

Please let me know if you need any other details. 

Thanks in advance.

**Comment by hgot07** [comment]
Upgrading the radsecproxy is strongly recommended. 1.8.1 is too old, and likely vulnerable.

**Comment by chaitus84** [comment]
I have tried with radsecproxy 1.10 as well and the same issue is observed
in 1.10 as well.

**Comment by hgot07** [comment]
Is the radsecproxy linked with openssl 1.1.1 or newer?

**Comment by chaitus84** [comment]
Following is the openssl version i am using.

OpenSSL> version
OpenSSL 1.0.1f 6 Jan 2014

If I add a non ECDHE/DHE cipher to the rasdsecproxy, the handshake goes
through fine without any issues.

If I add the following cipher: "TLS_RSA_WITH_AES_256_GCM_SHA384" handshake
is successful.

Following is the list of the ciphers the handshake is failing:

DHE-RSA-AES128-GCM-SHA256
DHE-RSA-AES256-GCM-SHA384
ECDHE-ECDSA-AES128-GCM-SHA256
ECDHE-ECDSA-AES256-GCM-SHA384
ECDHE-RSA-AES128-GCM-SHA256
ECDHE-RSA-AES256-GCM-SHA384

**Comment by hgot07** [comment]
You have to use openssl 1.1.1 or newer. TLS 1.3 won't work with older versions (which may have some severe vulnerabilities).

**Comment by hgot07** [comment]
Tried `ldd radsecproxy` ?

**Comment by chaitus84** [comment]
This is the output of ldd radsecproxy

root@Ubuntu3390:~/radsecproxy-1.10.0# ldd radsecproxy
        linux-vdso.so.1 =>  (0x00007ffdff526000)
        libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007fb37bf20000)
        libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007fb37bb43000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fb37b927000)
        libnettle.so.4 => /usr/lib/x86_64-linux-gnu/libnettle.so.4 (0x00007fb37b6f8000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb37b4da000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb37b114000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb37af10000)
        /lib64/ld-linux-x86-64.so.2 (0x000056151529b000)

**Comment by hgot07** [comment]
It seems your radsecproxy command has been linked with a very old libssl 1.0.0.

**Comment by chaitus84** [comment]
Thank you. I will try to find this out and revert.

**Comment by chaitus84** [comment]
After adding the correct dependency to radsecproxy, the connection is succesful. Thanks a lot @hgot07 for guiding me. Appreciate your help.
