### ISSUE TITLE
certificateNameCheck fails against SAN with wildcard

### ISSUE THREAD

**Issue by hgot07** [radsecproxy/radsecproxy#149]
Symptom:
When "certificateNameCheck on" and the server FQDN is matched against a domainname with wildcard in SAN, the name check fails.

Tested versions (client): 1.10.0 and 1.10.1

Details:
Suppose both srv1.example.com and srv2.example.com point to the same RadSec end-point.
Server certificate contains SAN=DNS: srv1.example.com, DNS:*.example.com

If a client attempts connection using server name srv1.example.com, the name check succeeds.

If a client attempts connection using server name srv2.example.com, radsecproxy produces an error "certnamecheck: No subjectaltname matching host srv2.example.com".

Is this intended or simply due to the lack of feature?

**Comment by fmauchle** [comment]
Yes this is a lacking feature. We actually already discovered this during thie IETF118 hackathon. It's on my todo list.

**Comment by hgot07** [comment]
Ah, I see. Sorry for my overlooking the situation. 
Thanks in advance for adding the feature.

**Comment by CyB0rgg** [comment]
This issue has been closed, is it still the intention to include it in the next major release ?

**Comment by fmauchle** [comment]
Yes, the code for wildcard certificates has been merged to the master branch and will thus be included in the next release (see ChangeLog in the master branch)

**Comment by CyB0rgg** [comment]
> Yes, the code for wildcard certificates has been merged to the master branch and will thus be included in the next release (see ChangeLog in the master branch)

Thanks Fabian, this is much needed and anticipated indeed !
