### ISSUE TITLE
make check fails for v1.71 release due to missing sting.h library

### ISSUE THREAD

**Issue by spgreen** [radsecproxy/radsecproxy#17]
When running make check in Ubuntu 18.04LTS, I receive an ```implicit declaration of function ‘strcmp’``` error which indicates a missing ```#include <string.h>``` library within ```tests/t_fticks.c```.

It has been fixed within the radsecproxy master branch by the #14 branch but the issue still exists within the [1.7.1 release](https://github.com/radsecproxy/radsecproxy/releases/download/1.7.1/radsecproxy-1.7.1.tar.gz) download. Would it be possible to update the 1.7.1 release package with the fix?

Error:
```
admin@localhost:~/radsecproxy-1.7.1$ make check
Making check in tests
make[1]: Entering directory '/home/admin/radsecproxy-1.7.1/tests'
make  t_fticks
make[2]: Entering directory '/home/admin/radsecproxy-1.7.1/tests'
gcc -DPACKAGE_NAME=\"radsecproxy\" -DPACKAGE_TARNAME=\"radsecproxy\" -DPACKAGE_VERSION=\"1.7.1\" -DPACKAGE_STRING=\"radsecproxy\ 1.7.1\" -DPACKAGE_BUGREPORT=\"https://radsecproxy.github.io\" -DPACKAGE_URL=\"\" -DPACKAGE=\"radsecproxy\" -DVERSION=\"1.7.1\" -DHAVE_MALLOPT=1 -DHAVE_LIBNETTLE=1 -DUSE_OPENSSL=1 -I.    -g -Wall -Werror -Wall -pedantic -Wno-long-long -pthread -DRADPROT_UDP -DRADPROT_TCP -DRADPROT_TLS -DRADPROT_DTLS -g -O2 -MT t_fticks.o -MD -MP -MF .deps/t_fticks.Tpo -c -o t_fticks.o t_fticks.c
t_fticks.c: In function ‘_check_hash’:
t_fticks.c:17:7: error: implicit declaration of function ‘strcmp’ [-Werror=implicit-function-declaration]
   if (strcmp(hash, (const char *) buf) != 0)
       ^~~~~~
cc1: all warnings being treated as errors
Makefile:515: recipe for target 't_fticks.o' failed
```

**Comment by fmauchle** [comment]
> Would it be possible to update the 1.7.1 release package with the fix?

As this affects code under revision control, I want to keep the release tarball in sync with the git tag. 
I'm planning on releasing a maintenance release soon(ish) as there are a number of build issues that need to be addressed.

**Comment by spgreen** [comment]
Okay that makes sense; looking forward to the maintenance release.

Cheers,
Simon
