### ISSUE TITLE
make on cygwin

### ISSUE THREAD

**Issue by plivnik** [radsecproxy/radsecproxy#18]
I am not able to make on Cygwin.
Error messages:
`debug.c:156:29: error: format '%ld' expects argument of type '
__pthread_t *}' [-Werror=format=]
         sprintf(tidbuf, "(%ld) %s", pthread_self(), format);

radsecproxy.c:79:12: error: 'optind' redeclared without dllimport attribute: previous dllimport ignored [-Werror=attribu
tes]
 extern int optind;
            ^~~~~~
radsecproxy.c:80:14: error: 'optarg' redeclared without dllimport attribute: previous dllimport ignored [-Werror=attribu
tes]
 extern char *optarg;
              ^~~~~~
radsecproxy.c:93:88: error: 'dtlsinit' undeclared here (not in a function); did you mean 'tlsinit'?
 static const struct protodefs *(*protoinits[])(uint8_t) = { udpinit, tlsinit, tcpinit, dtlsinit };
                                                                                        ^~~~~~~~
                                                                                        tlsinit
radsecproxy.c: In function 'createlistener':
radsecproxy.c:1969:45: error: 'IPV6_RECVPKTINFO' undeclared (first use in this function); did you mean 'IPV6_PKTINFO'?
             if (setsockopt(s, IPPROTO_IPV6, IPV6_RECVPKTINFO, &on, sizeof(on)) == -1)
                                             ^~~~~~~~~~~~~~~~
                                             IPV6_PKTINFO
radsecproxy.c:1969:45: note: each undeclared identifier is reported only once for each function it appears in
radsecproxy.c:1969:45: error: passing argument 3 of 'setsockopt' makes integer from pointer without a cast [-Werror=int-
conversion]
In file included from radsecproxy.c:37:0:
/usr/include/sys/socket.h:36:7: note: expected 'int' but argument is of type 'const struct protodefs * (**)(uint8_t) {ak
a const struct protodefs * (**)(unsigned char)}'
   int setsockopt (int __s, int __level, int __optname, const void *optval,
       ^~~~~~~~~~

util.c: In function 'enable_keepalive':
util.c:132:36: error: 'TCP_KEEPCNT' undeclared (first use in this function); did you mean 'TCP_NOOPT'?
     if(setsockopt(socket, SOL_TCP, TCP_KEEPCNT, &optval, optlen) < 0) {
                                    ^~~~~~~~~~~
                                    TCP_NOOPT
util.c:132:36: note: each undeclared identifier is reported only once for each function it appears in
util.c:136:36: error: 'TCP_KEEPIDLE' undeclared (first use in this function); did you mean 'TCP_KEEPCNT'?
     if(setsockopt(socket, SOL_TCP, TCP_KEEPIDLE, &optval, optlen) < 0) {
                                    ^~~~~~~~~~~~
                                    TCP_KEEPCNT
util.c:140:36: error: 'TCP_KEEPINTVL' undeclared (first use in this function); did you mean 'TCP_KEEPCNT'?
     if(setsockopt(socket, SOL_TCP, TCP_KEEPINTVL, &optval, optlen) < 0) {
                                    ^~~~~~~~~~~~~
                                    TCP_KEEPCNT

`
Thanks for help
Mike

**Comment by fmauchle** [comment]
Could you specify your exact version of cygwin please?

And just for reference: was there a version of radsecproxy that did successfully compile in the past with your environment?

**Comment by fmauchle** [comment]
Version 1.7.2 should how compile on cygwin. Thought I couln'd do detailed testing.
