### ISSUE TITLE
Allow rewrites to add attributes if they do not already exist

### ISSUE THREAD

**Issue by ghalse** [radsecproxy/radsecproxy#19]
At the moment the rewrite block allows you to manipulate attributes in a number of ways. However, there is no way to express "add this attribute if it does not already exist in the request/reply".

This semantic would be useful for Operator-Name. At the moment the only way to ensure Operator-Name is consistently added is to remove it and then re-add it, which potentially loses some information.

It would be nicer if we could add an Operator-Name if the RADIUS client did not already send one whilst preserving any that were sent. This handles the case where some clients (e.g. Windows NPS) are completely incapable of handling this correctly whereas others (e.g. FreeRADIUS) do it perfectly.

A reasonably neat way of implementing it would be to special case modifyAttribute so that it could match a missing attribute and add it, something like this:

  modifyAttribute 126://1example.ac.za/

and then perhaps as an extension, remove a matching attribute, although that might be harder to express syntactically. Alternatively, it could be done as a flag on addAttribute, or as a new option entirely (e.g. supplementAttribute).

**Comment by fmauchle** [comment]
+1
I've come across this idea too, with exactly this use-case.

**Comment by fmauchle** [comment]
Implemented in branch [rewrite-attribute](https://github.com/radsecproxy/radsecproxy/tree/rewrite-attribute).
Please test.

**Comment by ghalse** [comment]
You've got a typo on [line 2648](https://github.com/radsecproxy/radsecproxy/blob/774236f0c2a290df22ff70da76cf4bc2b492a1e0/radsecproxy.c#L2648), resulting in the error:
```
getgenericconfig: block rewrite sp-to-eduroam-out: supplementAttribute = 126:1example.ac.za
configuration error in block rewrite sp-to-eduroam-out, unknown option SupplementVendorAttribute
configuration error, unknown option SupplementVendorAttribute
```
