### ISSUE TITLE
logging to syslog broken in 1.7.2

### ISSUE THREAD

**Issue by Thomas-1985** [radsecproxy/radsecproxy#22]
Hi

OS: Ubuntu 16.04 LTS
Radsecproxy: 1.7.2 (from PPA https://launchpad.net/~tenet/+archive/ubuntu/radsecproxy)
Syslog: 3.5.6-2.1

I just upgraded from 1.6.8 to 1.7.2 and noticed, that the syslog loggin doesn't work anymore.

-I didn't change the syslog or radsecproxy config after the upgrade
-I tested with different syslog facilities (it was set to LOG_LOCAL1) but no change
LogDestination x-syslog:///LOG_LOCAL1

-When i set "LogDestination file:////var/log/radsecproxy.log", logging works without issues

Does somebofdy have a clue on how to debug further?

Cheers

Thomy

**Comment by Thomas-1985** [comment]
I verified that its not the syslog component on my server:

logger -p local1.notice "Test"
This gets logged to the radsecproxy.log and to my syslog server, so my syslog rules seem to work.

**Comment by fmauchle** [comment]
Seems to be an issue between systemd and syslog-ng
(works if using default rsyslog in ubuntu as well as if radsecproxy is started on the command line)

These settings should fix this for Ubuntu 16.04 LTS:
1. set `ForwardToSyslog=yes` in /etc/systemd/journald.conf
2. add `unix-dgram("/run/systemd/journal/syslog")` to your sources in /etc/syslog-ng/syslog-ng.conf

**Comment by Thomas-1985** [comment]
Yeah this works.
Thanks a lot! :)
