### ISSUE TITLE
Log is full of "replyh: got status server response" since 1.7.2

### ISSUE THREAD

**Issue by bgernert** [radsecproxy/radsecproxy#23]
Hi,
I upgraded radsecproxy from 1.6.9 to 1.7.2. My debug-level is set to "3", because I want to log every successful and unsuccessful authentication attempt (for statistics analysis). But starting with 1.7.2 I see lots of "replyh: got status server response" messages spamming my logfile. So would it be possible to put this debug message in a higher debug level (e.g. 4)?

I also tried to set up "f-ticks", but since I am only able to log to a file, f-ticks seems not working for me.

**Comment by rpaffrath** [comment]
Hi,

I don’t agree with you.

As an infrastructure provider for eduroam with over 400 client/server status server responses are essential for me to find out whether 
an eduroam identity provider (idp) is still available. If there is no access request you never know whether the tls connection to idp is still working.
Increasing the debug level to 4 would mean for me spamming my logfile with full off access-request messages what I really don’t need to check whether 
the idp is available.

> On 16. Nov 2018, at 08:17, Björn Gernert <notifications@github.com> wrote:
> 
> Hi,
> I upgraded radsecproxy from 1.6.9 to 1.7.2. My debug-level is set to "3", because I want to log every successful and unsuccessful authentication attempt (for statistics analysis). But starting with 1.7.2 I see lots of "replyh: got status server response" messages spamming my logfile. So would it be possible to put this debug message in a higher debug level (e.g. 4)?
> 
> I also tried to set up "f-ticks", but since I am only able to log to a file, f-ticks seems not working for me.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Mit freundlichen Grüßen/Best regards
   Ralf Paffrath
— 
Verein zur Förderung eines Deutschen Forschungsnetzes e.V.
Alexanderplatz 1, D - 10178 Berlin

eduroam Beratung:
Tel.: 030 88 42 99 91 21
eduroam technischer Support:
Tel.: 030 88 42 99 91 20

email:eduroam@dfn.de

Fax: 030 88 42 99 370
http://www.dfn.de

Vorstand: Prof. Dr. Hans-Joachim Bungartz (Vorsitzender), Dr. Rainer Bockholt, Christian Zens
Geschäftsführung: Dr. Christian Grimm, Jochem Pattloch

**Comment by bgernert** [comment]
Hi,
okay, I get your point. How did you monitor the connection before 1.7.2? Was there some other functionality?

Would it be practicable to design a more timer driven functionality for this purpose? E.g. a list where all active connections are stored with a 'last seen' field. So we can define a timeout and only if this timeout occurs a log message is created.

**Comment by rpaffrath** [comment]
Hi,

> On 16. Nov 2018, at 11:39, Björn Gernert <notifications@github.com> wrote:
> 
> Hi,
> okay, I get your point. How did you monitor the connection before 1.7.2? Was there some other functionality?

I patched the code. 

> 
> Would it be practicable to design a more timer driven functionality for this purpose? E.g. a list where all active connections are stored with a 'last seen' field. So we can define a timeout and only if this timeout occurs a log message is created.

There must be already something similar coded. If there are access requests for an idp you will not see status server for that idp.
Now, if there are no access request radsecproxy produces status server messages approx. every 30 seconds. 
I guess there is already a timer inside the code.

Maybe Fabian can give some more comments

**Comment by fmauchle** [comment]
> If there are access requests for an idp you will not see status server for that idp.

That is correct. radsecproxy currently only sends status server if there are no responses received from a server (either because there are no requests, or because they are lost)

I'm currently working (more or less done) on adding additional options to do only minimal status server. Eg only when there are response timeouts and no other responses received from a server.
