### ISSUE TITLE
Non-portable use of time_t/abs()

### ISSUE THREAD

**Issue by paravoid** [radsecproxy/radsecproxy#28]
Commit 25c2a4ae69232a01c4e5abb490bd13e42868f2d2 restructured the connect-timeout code. The repetition of constructs like `now.tv_sec - start.tv_sec` is unfortunate IMHO, but in any case, it introduced a portability bug: for Y2038 reasons, `time_t` is 64-bit on some systems like FreeBSD 12 on x86_64, and thus the call to `wait = abs(now.tv_sec - start.tv_sec)` on all of tcp.c/tls.c/dtls.c produces a build failure, since `abs()` only operates on ints, not longs.

I don't really see why `abs()` is being used there at all. If the intention is to catch cases where now < start and thus now - start < 0? If so, why would you want to convert e.g. -6 to 6? The code has an `if (wait < 1) sleep(2)` later on, so that would also catch negative values, right?

**Comment by fmauchle** [comment]
if abs() isn't used, yes it would still wait, but with too short timers, resulting in aggressive reconnects in case the a connection is unstable (closed within a few seconds after it is established).
But I had planned to restructure this timing code anyway, especially because we have the same code in 3 locations

**Comment by paravoid** [comment]
I still don't understand it -- if it was closed within a few seconds after it was established then `now - start` will be a few (positive) seconds, not negative, right?

But if you're working on it nevertheless... no need for me to understand it :) Just take into account that `time_t` is its own type and may vary between architectures, platforms, libc versions etc.
