### ISSUE TITLE
Building radsecproxy for macOS

### ISSUE THREAD

**Issue by alexsharaz** [radsecproxy/radsecproxy#33]
Has anyone built radsecproxy for macOS ? looking for sone instructions. ./conofigure fails for nettle_sha256 library

Rgds
Alex

**Comment by alexsharaz** [comment]
o.k. used brew to install nettle, pointed at openssl libraries using --with-ssl ..... and get

mv -f .deps/debug.Tpo .deps/debug.Po
gcc -DPACKAGE_NAME=\"radsecproxy\" -DPACKAGE_TARNAME=\"radsecproxy\" -DPACKAGE_VERSION=\"1.7.2\" -DPACKAGE_STRING=\"radsecproxy\ 1.7.2\" -DPACKAGE_BUGREPORT=\"https://radsecproxy.github.io\" -DPACKAGE_URL=\"\" -DPACKAGE=\"radsecproxy\" -DVERSION=\"1.7.2\" -DHAVE_LIBNETTLE=1 -DUSE_OPENSSL=1 -I.  -DSYSCONFDIR=\"/usr/local/etc\" -I/usr/local/opt/curl/include -g -Wall -Werror -fno-strict-aliasing -I/usr/local/Cellar/openssl/1.0.2r//include -I/usr/local/Cellar/openssl/1.0.2r//include/openssl -Wall -pedantic -Wno-long-long -pthread -DRADPROT_UDP -DRADPROT_TCP -DRADPROT_TLS -DRADPROT_DTLS -g -O2 -MT dtls.o -MD -MP -MF .deps/dtls.Tpo -c -o dtls.o dtls.c
dtls.c:408:80: error: use of undeclared identifier 'IPV6_PKTINFO'
        } else if(ctrlhdr->cmsg_level == IPPROTO_IPV6 && ctrlhdr->cmsg_type == IPV6_RECVPKTINFO) {
                                                                               ^
./radsecproxy.h:40:26: note: expanded from macro 'IPV6_RECVPKTINFO'
#define IPV6_RECVPKTINFO IPV6_PKTINFO
                         ^
dtls.c:543:20: error: absolute value function 'abs' given an argument of type 'long' but has parameter of type 'int' which may cause truncation of value
      [-Werror,-Wabsolute-value]
            wait = abs(now.tv_sec - start.tv_sec);
                   ^
dtls.c:543:20: note: use function 'labs' instead
            wait = abs(now.tv_sec - start.tv_sec);
                   ^~~
                   labs
2 errors generated.
make[1]: *** [dtls.o] Error 1
make: *** [all-recursive] Error 1

**Comment by fmauchle** [comment]
the second half is already known #28 and will be fixed shortly.
for the first half I have to check which socket APIs macOS actually supports.

**Comment by fmauchle** [comment]
The required socket API can be enabled with `CFLAGS="-D__APPLE_USE_RFC_3542"`.

However, macOS X doesn't like the posix way to daemonize.
You can get it co compile by adding `-Wno-deprecated-declarations` to the CFLAGS, but Apple considers it unsafe.

**Comment by alexsharaz** [comment]
Unfortunately 

gcc -DPACKAGE_NAME=\"radsecproxy\" -DPACKAGE_TARNAME=\"radsecproxy\" -DPACKAGE_VERSION=\"1.7.2\" -DPACKAGE_STRING=\"radsecproxy\ 1.7.2\" -DPACKAGE_BUGREPORT=\"https://radsecproxy.github.io\" -DPACKAGE_URL=\"\" -DPACKAGE=\"radsecproxy\" -DVERSION=\"1.7.2\" -DHAVE_LIBNETTLE=1 -DUSE_OPENSSL=1 -I.  -DSYSCONFDIR=\"/usr/local/etc\" -I/usr/local/opt/curl/include -g -Wall -Werror -fno-strict-aliasing -I/usr/local/Cellar/openssl/1.0.2r/include -I/usr/local/Cellar/openssl/1.0.2r/include/openssl -Wall -pedantic -Wno-long-long -pthread -DRADPROT_UDP -DRADPROT_TCP -DRADPROT_TLS -DRADPROT_DTLS -D__APPLE_USE_RFC_3542  -Wno-deprecated-declarations -MT dtls.o -MD -MP -MF .deps/dtls.Tpo -c -o dtls.o dtls.c
dtls.c:543:20: error: absolute value function 'abs' given an argument of type 'long' but has parameter of type 'int'
      which may cause truncation of value [-Werror,-Wabsolute-value]
            wait = abs(now.tv_sec - start.tv_sec);
                   ^
dtls.c:543:20: note: use function 'labs' instead
            wait = abs(now.tv_sec - start.tv_sec);
                   ^~~
                   labs
1 error generated.
make[1]: *** [dtls.o] Error 1
make: *** [all-recursive] Error 1

Wit both those entries in there

Rgds
Alex

**Comment by fmauchle** [comment]
This is issue #28 which has very recently been fixed. Please use current master branch.

**Comment by alexsharaz** [comment]
Instaling autoconf from brew  and running to generate configure I get

alexsmacpro:radsecproxy-master alexsharaz$ autoconf -v
autoconf: running /usr/local/Cellar/autoconf/2.69/bin/autom4te -v --language=autoconf --output=configure configure.ac
autom4te: formatting traces for `/var/folders/p7/21sdw2jx2flc6y6561f69pyr0000gn/T//am4trQLsPb/dependencies': include, m4_include
autom4te: up_to_date (autom4te.cache/traces.0): up to date
autom4te: the trace request object is:
autom4te: $VAR1 = bless( [
autom4te:                  '0',
autom4te:                  1,
autom4te:                  [
autom4te:                    '/usr/local/Cellar/autoconf/2.69/share/autoconf'
autom4te:                  ],
autom4te:                  [
autom4te:                    '/usr/local/Cellar/autoconf/2.69/share/autoconf/autoconf/autoconf.m4f',
autom4te:                    'configure.ac'
autom4te:                  ],
autom4te:                  {
autom4te:                    'AC_INIT' => 1,
autom4te:                    'AM_GNU_GETTEXT_INTL_SUBDIR' => 1,
autom4te:                    'AC_CANONICAL_BUILD' => 1,
autom4te:                    'AC_CONFIG_LIBOBJ_DIR' => 1,
autom4te:                    'AM_PROG_CC_C_O' => 1,
autom4te:                    'AC_CANONICAL_TARGET' => 1,
autom4te:                    'AC_FC_FREEFORM' => 1,
autom4te:                    'AM_PROG_CXX_C_O' => 1,
autom4te:                    'AM_XGETTEXT_OPTION' => 1,
autom4te:                    'AM_PROG_F77_C_O' => 1,
autom4te:                    'm4_pattern_allow' => 1,
autom4te:                    'AM_GNU_GETTEXT' => 1,
autom4te:                    'AM_PATH_GUILE' => 1,
autom4te:                    'AC_PROG_LIBTOOL' => 1,
autom4te:                    'AC_CANONICAL_SYSTEM' => 1,
autom4te:                    'AM_POT_TOOLS' => 1,
autom4te:                    '_AM_COND_IF' => 1,
autom4te:                    'AM_SILENT_RULES' => 1,
autom4te:                    'm4_pattern_forbid' => 1,
autom4te:                    'AM_MAKEFILE_INCLUDE' => 1,
autom4te:                    'AM_PROG_FC_C_O' => 1,
autom4te:                    'AM_INIT_AUTOMAKE' => 1,
autom4te:                    'AC_REQUIRE_AUX_FILE' => 1,
autom4te:                    '_AM_COND_ELSE' => 1,
autom4te:                    'AM_PROG_MOC' => 1,
autom4te:                    'AC_SUBST' => 1,
autom4te:                    'LT_SUPPORTED_TAG' => 1,
autom4te:                    'AM_NLS' => 1,
autom4te:                    'AC_FC_PP_DEFINE' => 1,
autom4te:                    'AC_CONFIG_HEADERS' => 1,
autom4te:                    'AC_SUBST_TRACE' => 1,
autom4te:                    'AC_CONFIG_AUX_DIR' => 1,
autom4te:                    'include' => 1,
autom4te:                    'AC_CONFIG_FILES' => 1,
autom4te:                    'AC_FC_SRCEXT' => 1,
autom4te:                    'm4_sinclude' => 1,
autom4te:                    '_AM_COND_ENDIF' => 1,
autom4te:                    'AC_LIBSOURCE' => 1,
autom4te:                    'LT_CONFIG_LTDL_DIR' => 1,
autom4te:                    'AC_FC_PP_SRCEXT' => 1,
autom4te:                    'AC_DEFINE_TRACE_LITERAL' => 1,
autom4te:                    'AM_PROG_AR' => 1,
autom4te:                    '_AM_MAKEFILE_INCLUDE' => 1,
autom4te:                    'LT_INIT' => 1,
autom4te:                    'AC_CONFIG_SUBDIRS' => 1,
autom4te:                    'AM_AUTOMAKE_VERSION' => 1,
autom4te:                    'AH_OUTPUT' => 1,
autom4te:                    'AC_CONFIG_LINKS' => 1,
autom4te:                    'AM_MAINTAINER_MODE' => 1,
autom4te:                    'AC_CANONICAL_HOST' => 1,
autom4te:                    '_LT_AC_TAGCONFIG' => 1,
autom4te:                    'sinclude' => 1,
autom4te:                    '_m4_warn' => 1,
autom4te:                    'm4_include' => 1,
autom4te:                    '_AM_SUBST_NOTMAKE' => 1,
autom4te:                    'AM_CONDITIONAL' => 1,
autom4te:                    'AM_ENABLE_MULTILIB' => 1
autom4te:                  }
autom4te:                ], 'Autom4te::Request' );
autom4te: formatting traces for `/var/folders/p7/21sdw2jx2flc6y6561f69pyr0000gn/T//am4trQLsPb/warnings': _m4_warn
autom4te: reading /var/folders/p7/21sdw2jx2flc6y6561f69pyr0000gn/T//am4trQLsPb/warnings
autom4te: creating configure
autom4te: formatting traces for `/var/folders/p7/21sdw2jx2flc6y6561f69pyr0000gn/T//am4trQLsPb/patterns': m4_pattern_allow, m4_pattern_forbid
autom4te: forbidden tokens: ^_?A[CHUM]_|_AC_|^LIBOBJS$|^_?m4_|^dnl$|^_?AS_
autom4te: forbidden token : ^LIBOBJS$ => do not use LIBOBJS directly, use AC_LIBOBJ (see section `AC_LIBOBJ vs LIBOBJS'
autom4te: allowed   tokens: ^AS_FLAGS$|^SHELL$|^PATH_SEPARATOR$|^PACKAGE_NAME$|^PACKAGE_TARNAME$|^PACKAGE_VERSION$|^PACKAGE_STRING$|^PACKAGE_BUGREPORT$|^PACKAGE_URL$|^exec_prefix$|^prefix$|^program_transform_name$|^bindir$|^sbindir$|^libexecdir$|^datarootdir$|^datadir$|^sysconfdir$|^sharedstatedir$|^localstatedir$|^includedir$|^oldincludedir$|^docdir$|^infodir$|^htmldir$|^dvidir$|^pdfdir$|^psdir$|^libdir$|^localedir$|^mandir$|^PACKAGE_NAME$|^PACKAGE_TARNAME$|^PACKAGE_VERSION$|^PACKAGE_STRING$|^PACKAGE_BUGREPORT$|^PACKAGE_URL$|^DEFS$|^ECHO_C$|^ECHO_N$|^ECHO_T$|^LIBS$|^build_alias$|^host_alias$|^target_alias$|^build$|^build_cpu$|^build_vendor$|^build_os$|^host$|^host_cpu$|^host_vendor$|^host_os$|^target$|^target_cpu$|^target_vendor$|^target_os$|^CC$|^CFLAGS$|^LDFLAGS$|^LIBS$|^CPPFLAGS$|^CC$|^CC$|^CC$|^CC$|^ac_ct_CC$|^EXEEXT$|^OBJEXT$|^RANLIB$|^HAVE_MALLOPT$|^HAVE_LIBNETTLE$|^TARGET_CFLAGS$|^TARGET_LDFLAGS$|^LIBOBJS$|^LTLIBOBJS$
configure.ac:7: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

**Comment by fmauchle** [comment]
I think you will also need to install automake. Then simply call the autogen.sh script.

**Comment by alexsharaz** [comment]
.. and it all works!

Many thanks for your help. Now have RADSEC running  between macOS and Linux :-)

Rgds
Alex
