### ISSUE TITLE
Cannot use multiple address families with Source*

### ISSUE THREAD

**Issue by ghalse** [radsecproxy/radsecproxy#34]
The SourceUDP, SourceTCP, SourceTLS, and SourceDTLS options allow you to bind a specific source address for an outbound connection from radsecproxy. However because you can only specify one of each option, this effectively forces radsecproxy to use a specific address family for outbound connections.

Given the growing prevelence of dual-stacked hosts and the IPv6 support in other parts of the radsecproxy code, it would make sense to allow for the specification of separate IPv4 and and IPv6 source addresses.

This is useful on a host that is dual-stacked and binds multiple addresses in each address family for different purposes. You might want to ensure that outbound connections originate from a specific IPv4 and IPv6 address to match the inbound connections, but still support both IPv4 and IPv6 outbound connections.

This might be related to #21.

**Comment by fmauchle** [comment]
btw. specifying a DNS name that has both A and AAAA records should work fine.
But of course specifying them as address literals must not limit the address family used.

**Comment by ghalse** [comment]
> btw. specifying a DNS name that has both A and AAAA records should work fine.
With the caveat that DNS is only queried at boot, and radsecproxy will refuse to boot if the DNS lookup fails. We stopped using DNS-based entries for server and client blocks because of the risks associated with the latter.

However if DNS works for Source*, it might be a useful workaround for this problem since the DNS of things we control is typically more reliable.

**Comment by jornane** [comment]
> > btw. specifying a DNS name that has both A and AAAA records should work fine.
>
> With the caveat that DNS is only queried at boot, and radsecproxy will refuse to boot if the DNS lookup fails. We stopped using DNS-based entries for server and client blocks because of the risks associated with the latter.
>
> However if DNS works for Source*, it might be a useful workaround for this problem since the DNS of things we control is typically more reliable.

Yes, we use it that way. Combined with entries in /etc/hosts so startup won't fail on transient DNS failures. It feels a bit hackish though, I would also like the possibility to provide multiple families for Source*

**Comment by jornane** [comment]
@fmauchle why have you closed this issue?

**Comment by fmauchle** [comment]
this issue has been fixed and pushed to the master branch.

**Comment by jornane** [comment]
Ah yeah, ab15747. Thanks, nice!
