### ISSUE TITLE
Tunnel-Password attribute not reencrypted

### ISSUE THREAD

**Issue by twisted-pear** [radsecproxy/radsecproxy#35]
Hi, I was trying to have my radius server hand out WPA-PSKs per station MAC address, with hostapd as the AP and radsecproxy in between. The radius server sends an Accept message with an encrypted Tunnel-Password attribute (according to RFC 2868, Section 3.5) containing the PSK.

The function apparently responsible for encrypting and decrypting password attributes is `pwdcrypt()` in `radsecproxy.c`. However, it treats the Tunnel-Password attribute like the User-Password attribute, which is encrypted differently (as per RFC 2865, Section 5.2). Specifically, the first block of the xor-mask needs to be a hash over the shared secret, the authenticator AND the salt. The last one is ignored currently.

Furthermore, the "reencryption" for password attributes is never applied to responses in `replyh()`.

I hacked together a quick and dirty patch to fix both issues and, as far as I can tell, without breaking regular User-Password attributes. I am not sure if I used all the pointers to the secrets and authenticators correctly when I modified `replyh()`. I also just copied the salt and the tag field from the server's response instead of generating a different salt (which should probably be done). Here it is: [radsecproxy-tunnelpassword-fix.patch](https://gist.github.com/twisted-pear/62717129510d30d0102d72562f2fd916)

Works for me.

**Comment by fmauchle** [comment]
I've pushed a fix to master. However I currently don't have the facilities to test this. I would appreciate if you could give it a try and see if it works for you.

**Comment by twisted-pear** [comment]
Thanks for looking into this! I'm afraid I won't have a chance to wrestle with this before the weekend. I'll let you know.

**Comment by twisted-pear** [comment]
Hmm, skimming the commit/code, it seems that you are still only checking the messages to the RADIUS server for Tunnel-Password attributes. In my case the reply contains the Tunnel-Password Attribute to use as the PSK for WPA.

In fact, the RFC (2868) states that "It (the attribute) may only be included in an Access-Accept packet.". I missed that when I first looked into this... The Tunnel-Password attribute is always going to be in the server's response.

**Comment by fmauchle** [comment]
Thanks! I had totally missed that point, as the code already was handling the tunnel password attribute in some (albeit wrong) way.

**Comment by twisted-pear** [comment]
Ok, the latest commit fixes that. Thanks! I'll try to sit down this weekend to give it a try.

**Comment by twisted-pear** [comment]
I replaced my own patched version of radsecproxy with a build of the latest master branch and it worked like a charm. The Tunnel-Password that the server returns is correctly handled now. Thank you for fixing this.

**Comment by fmauchle** [comment]
Thanks for verifying!
