### ISSUE TITLE
Feature request: Log operator-name and/or Chargeable-User-Identity

### ISSUE THREAD

**Issue by ghalse** [radsecproxy/radsecproxy#36]
The use of anonymous outer identities and the increasing randomization of MAC addresses in the Calling-Station-Id, the current log entry line is becoming less useful.
```
Access-Accept for user anonymous@wf.ru.ac.za stationid ea-69-0a-64-01-aa from radius.ru.ac.za to rad04.example.ac.za (192.0.2.1)
```
In the above example both the username and the stationid are completely anonymous.

It would thus provide useful debugging and statistical information if radsecproxy logged the Operator-Name and Chargeable-User-Identity attributes if they are available.

**Comment by jornane** [comment]
This would be very useful for us as well.

**Comment by spgreen** [comment]
Hi all,

@vladimir-mencl-eresearch from REANNZ created a patch for the eXtending eduroam in Asia-Pacific 2 (XeAP2) Project that adds the Operator-Name and CUI into the radsecproxy logs if they are present. We added it to the [Docker image](https://hub.docker.com/r/spgreen/eduroam-radsecproxy) I setup for the project. The xeap2 tags contains the OpName and CUI patch.

**This is the patch in question:** https://github.com/spgreen/eduroam-radsecproxy-docker/blob/master/1.8.0-xeap2/patch/radsecproxy-log-opname-cui.diff

**Log output:**

```
Jul 15 09:23:02 2019: Access-Reject for user testuser@humid.edu.sg stationid 02-00-00-00-00-01 from tlr-00 to cricket.ac.nz (192.168.1.2) (Operator_Name 1cricket.ac.nz) (CUI )
Jul 15 09:23:06 2019: Access-Accept for user testuser@humid.edu.sg stationid 02-00-00-00-00-01 from tlr-00 to cricket.ac.nz (192.168.1.2) (Operator_Name 1cricket.ac.nz) (CUI 5eb26afb5f313224d7f3986e9b5f8d4bd7225e35)
````
The patch could be implemented to add said features into the official radseproxy repo.

**Comment by vladimir-mencl-eresearch** [comment]
Just to confirm, I'd be happy for my patch to be included in the main code base.
