### ISSUE TITLE
Resolving SAN Issuing Policy OID

### ISSUE THREAD

**Issue by mark-grayson** [radsecproxy/radsecproxy#43]
# Issue

Feature Request

# Description

In radsecproxy, version 1.7.2, with a WBA policy OID in a certificates Subject Alternative Name, only the certificate's URI is verifiable.  Subject Alternative Name OID values should be verifiable via Regex in the same manner as Common Name if the OID has been defined in the TLS block and is present in the certificate SAN.

## Background

This issue is being raised on behalf of Wireless Broadband Alliance.
WBA is currently evolving its WRIX RADIUS Roaming system to enable support of RADSEC.
RADSEC testing has been performed by multiple WBA members, including:
Accuris Networks, BSG Wireless, Cablelabs, Cisco and iPass/Pareteum

**Comment by fmauchle** [comment]
by 'Subject Alternative Name OID values' you are referring to the SAN registerdID?
from RFC5280:
```
   SubjectAltName ::= GeneralNames
   GeneralNames ::= SEQUENCE SIZE (1..MAX) OF GeneralName
   GeneralName ::= CHOICE {
(...)
        registeredID                    [8]     OBJECT IDENTIFIER }
```
However this would not require a regex match, but a simple OID match.
Neither would it depend on the TLS block, but just on the client/server `MatchCertificateAttribute` config.
