### ISSUE TITLE
Resolving DNS name to SAN IP Address

### ISSUE THREAD

**Issue by mark-grayson** [radsecproxy/radsecproxy#44]
# Issue

Feature Request

# Description

In radsecproxy, version 1.7.2, with a Subject Alternative Name IP Address in the peer certificate, the IP Address may not be checked against DNS or direct validation.  The peer's IP Address should be reverse-verified by DNS or simple Regex check if an IP Address is defined in the Certificate SAN.

# Notes

In Server Block:  Use Regex with MatchCertificateAttribute (CN) to validate CN (IP or FQDN) + block 'host' as IP uses IPADDR san check or as FQDN checks SAN DNSNAME when certificateNameCheck is 'on'

## Background

This issue is being raised on behalf of Wireless Broadband Alliance.
WBA is currently evolving its WRIX RADIUS Roaming system to enable support of RADSEC.
RADSEC testing has been performed by multiple WBA members, including:
Accuris Networks, BSG Wireless, Cablelabs, Cisco and iPass/Pareteum

**Comment by fmauchle** [comment]
SAN DNS  and SAN IP checks have already been implemented in radsecproxy 1.8.0.

Please check against the latest version and report back if you still think there are missing options.
