### ISSUE TITLE
Server CRL Validation

### ISSUE THREAD

**Issue by mark-grayson** [radsecproxy/radsecproxy#46]
# Issue

Defect

# Description

In radsecproxy 1.7.2, with a Kyrio CRL Distribution Points Extension included in a Radsec  Server Certificate, with CRLCheck enabled in the TLS block on the client, when a radsecproxy client makes a successful connection to a Radsec server, the Radsec client is unable to get the certificate CRL:depth=0:/CableLabs/OU=Test WBA WRIX Entity Certificate/CN=[fqdn] and certificate verify fails.  Radsec Clients and Servers must be able to verify a peer's CRL by querying the presented certificate's CRL Distribution List.

## Background

This issue is being raised on behalf of Wireless Broadband Alliance.
WBA is currently evolving its WRIX RADIUS Roaming system to enable support of RADSEC.
RADSEC testing has been performed by multiple WBA members, including:
Accuris Networks, BSG Wireless, Cablelabs, Cisco and iPass/Pareteum

**Comment by fmauchle** [comment]
radsecproxy does not fetch CRLs itself. Fetching CRL must be provided externally with tools such as [fetch-crl](https://linux.die.net/man/8/fetch-crl). You can then SIGHUP radsecproxy to reload those CRLs or set the CacheExpiry.

Granted, this fact is not very clear in the manpage.
