### ISSUE TITLE
Compilation fails under freebsd 12.0

### ISSUE THREAD

**Issue by nrh3** [radsecproxy/radsecproxy#48]
Rewrite.c compile fails under freebsd 12.0 as follows:

`rewrite.c:49:16: error: implicit declaration of function 'htonl' is invalid in
      C99 [-Werror,-Wimplicit-function-declaration]
        ival = htonl(ival);
               ^
rewrite.c:332:14: error: implicit declaration of function 'ntohl' is invalid in
      C99 [-Werror,-Wimplicit-function-declaration]
    vendor = ntohl(vendor);
             ^
rewrite.c:506:22: error: implicit declaration of function 'ntohl' is invalid in
      C99 [-Werror,-Wimplicit-function-declaration]
            vendor = ntohl(vendor);
`

This fixes the compile:
`
diff --git a/rewrite.c b/rewrite.c
index b292374..f0fd38c 100644
--- a/rewrite.c
+++ b/rewrite.c
@@ -1,6 +1,7 @@
 /* Copyright (c) 2019, SWITCH */
 /* See LICENSE for licensing information. */
 
+#include <arpa/inet.h>
 #include <ctype.h>
 #include <stdlib.h>
 #include <string.h>
`

**Comment by paravoid** [comment]
`htonl`/`ntohl` are documented as requiring an `<arpa/inet.h>` include, so yes, +1 :)

**Comment by jornane** [comment]
I've submitted a [patch to this project](https://github.com/radsecproxy/radsecproxy/pull/53) and a [patch to FreeBSD](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=240382) ports. Hopefully it'll make Q4. 🙂

**Comment by jornane** [comment]
Compiling with [security/libressl](https://www.freshports.org/security/libressl/) or [security/libressl-devel](https://www.freshports.org/security/libressl-devel/) should also work with #54

**Comment by fmauchle** [comment]
pull requests #53 and #54 merged
