### ISSUE TITLE
Minor: LDFLAGS overwritten in tests/Makefile.am

### ISSUE THREAD

**Issue by shartge** [radsecproxy/radsecproxy#52]
Debian uses several hardening options during package build, set by using the usual environment variables.

This fails for the test binaries, because tests/Makefile.am redefines the LDFLAGS variable, overwriting the external one. See https://salsa.debian.org/debian/radsecproxy/-/jobs/308286 for a log output.

A simple patch is attached, appending the original value of LDFLAGS to the redefined one.

[fix-LDFLAGS-for-tests.txt](https://github.com/radsecproxy/radsecproxy/files/3582590/fix-LDFLAGS-for-tests.txt)

**Comment by fmauchle** [comment]
patch pushed to master
