### ISSUE TITLE
No space allowed in realm regexp 

### ISSUE THREAD

**Issue by chris4git** [radsecproxy/radsecproxy#55]
I want to trap realms with trailing spaces but when I add a space in a realm regexp (as in "/\.fr *$/"), radsecproxy (1.8.0) complains :
configuration error, syntax error in line starting with realm
configuration error

The space should be allowed in realm regexp

**Comment by jornane** [comment]
I didn't test, but could it work with `\s` instead of a literal space?

(nitpick: you must escape the `.`, like `\.`)

**Comment by fmauchle** [comment]
Unfortunately I'm unable to reproduce this behaviour with the given example. A minimalist config:

```
client localhost {
    type udp
    secret test
}
realm "/.fr *$/" {
}
```


Does work as intended (radsecproxy -d5 ...):
```
...
confrealm_cb called for realm /.fr *$/
addrealm: added realm /.fr *$
...
Sep 25 08:32:03 2019: radsecproxy 1.8.0 starting
```

Maybe your actual config is more complex and there are other issues present? Or we might have a specific platform issue?

(another nitpik: is this regex really what you want? it would also match ".fr" without any whitespace in it)

**Comment by chris4git** [comment]
Hmm, you can't reproduce because I haven't put quotes around the regexp in my configuration file but  I put quotes to describe the issue. With quotes around the regexp in the configuration file it works !
And you're right : it doesn't do exactly what I want ;-)
