### ISSUE TITLE
secret field content erroneously  interpreted

### ISSUE THREAD

**Issue by chris4git** [radsecproxy/radsecproxy#56]
it seems the content of the secret string is interpreted when it contains a "%" :

when a client (or server) declaration contains
secret   fht8CD%E7am

it is interpreted as
getgenericconfig: block client xxxx.yyyyy: secret = fht8CDçam

One can see "%E7" is translated as the "ç" character.

Result :  clients and/or servers who use a secret containing substring "%hh" are rejected !

I suspect the function unhex() in gconfig.c to be the culprit...

**Comment by fmauchle** [comment]
As already reported on the mailing list, escaping % is explained in the manpage

> If you want to write a % and not use this decoding, you may of course write % in hex; i.e., %25.
