### ISSUE TITLE
Feature request: Add actual cipher suites

### ISSUE THREAD

**Issue by Jack1232323** [radsecproxy/radsecproxy#60]
Hello guys,

I would like to raise a feature request.
The story: we use radsec for auth and it stopped working, after we upgraded one product, which was authenticating. It shows that the producer removed all "old" cipher suites, and is now using just some, which are not supported with the latest radsec version.

These are the cipher suites which are not supported and I would like to get implemented:

![image](https://user-images.githubusercontent.com/57178434/67855625-1104fa00-fb13-11e9-9e17-6db999d71173.png)

Thanks in advance :)

**Comment by shartge** [comment]
radsecproxy uses whatever cipher the SSL library it is linked with provides.

On Debian 10 for example using OpenSSL 1.1.1d the ciphers you mentioned are available.
Here, output from `testssl.sh -E my-deb10-radsec-server`:

```
Testing ciphers per protocol via OpenSSL plus sockets against the server, ordered by encryption strength 

Hexcode  Cipher Suite Name (OpenSSL)       KeyExch.   Encryption  Bits     Cipher Suite Name (IANA/RFC)
-----------------------------------------------------------------------------------------------------------------------------
SSLv2  
SSLv3  
TLS 1  
 xc014   ECDHE-RSA-AES256-SHA              ECDH 521   AES         256      TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                 
 x35     AES256-SHA                        RSA        AES         256      TLS_RSA_WITH_AES_256_CBC_SHA                       
 xc013   ECDHE-RSA-AES128-SHA              ECDH 521   AES         128      TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA                 
 x2f     AES128-SHA                        RSA        AES         128      TLS_RSA_WITH_AES_128_CBC_SHA                       
TLS 1.1  
 xc014   ECDHE-RSA-AES256-SHA              ECDH 521   AES         256      TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                 
 x35     AES256-SHA                        RSA        AES         256      TLS_RSA_WITH_AES_256_CBC_SHA                       
 xc013   ECDHE-RSA-AES128-SHA              ECDH 521   AES         128      TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA                 
 x2f     AES128-SHA                        RSA        AES         128      TLS_RSA_WITH_AES_128_CBC_SHA                       
TLS 1.2  
 xc030   ECDHE-RSA-AES256-GCM-SHA384       ECDH 521   AESGCM      256      TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384              
 xc028   ECDHE-RSA-AES256-SHA384           ECDH 521   AES         256      TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384              
 xc014   ECDHE-RSA-AES256-SHA              ECDH 521   AES         256      TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                 
 xcca8   ECDHE-RSA-CHACHA20-POLY1305       ECDH 521   ChaCha20    256      TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256        
 x9d     AES256-GCM-SHA384                 RSA        AESGCM      256      TLS_RSA_WITH_AES_256_GCM_SHA384                    
 x3d     AES256-SHA256                     RSA        AES         256      TLS_RSA_WITH_AES_256_CBC_SHA256                    
 x35     AES256-SHA                        RSA        AES         256      TLS_RSA_WITH_AES_256_CBC_SHA                       
 xc02f   ECDHE-RSA-AES128-GCM-SHA256       ECDH 521   AESGCM      128      TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256              
 xc027   ECDHE-RSA-AES128-SHA256           ECDH 521   AES         128      TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256              
 xc013   ECDHE-RSA-AES128-SHA              ECDH 521   AES         128      TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA                 
 x9c     AES128-GCM-SHA256                 RSA        AESGCM      128      TLS_RSA_WITH_AES_128_GCM_SHA256                    
 x3c     AES128-SHA256                     RSA        AES         128      TLS_RSA_WITH_AES_128_CBC_SHA256                    
 x2f     AES128-SHA                        RSA        AES         128      TLS_RSA_WITH_AES_128_CBC_SHA                       
TLS 1.3  
 x1302   TLS_AES_256_GCM_SHA384            ECDH 253   AESGCM      256      TLS_AES_256_GCM_SHA384                             
 x1303   TLS_CHACHA20_POLY1305_SHA256      ECDH 253   ChaCha20    256      TLS_CHACHA20_POLY1305_SHA256                       
 x1301   TLS_AES_128_GCM_SHA256            ECDH 253   AESGCM      128      TLS_AES_128_GCM_SHA256    
```

**Comment by Jack1232323** [comment]
Thanks for the answer.

Previously we used SLES 12, now we tested this on another machine with SLES 15:

Output from ` testssl.sh       2.8`

`Hexcode  Cipher Suite Name (OpenSSL)       KeyExch.  Encryption Bits
------------------------------------------------------------------------
SSLv2 Local problem: /usr/bin/openssl doesn't support "s_client -ssl2"
SSLv3 Local problem: /usr/bin/openssl doesn't support "s_client -ssl3"
TLS 1
 xc014   ECDHE-RSA-AES256-SHA              ECDH 253   AES       256
 x35     AES256-SHA                        RSA        AES       256
 xc013   ECDHE-RSA-AES128-SHA              ECDH 253   AES       128
 x2f     AES128-SHA                        RSA        AES       128
TLS 1.1
 xc014   ECDHE-RSA-AES256-SHA              ECDH 253   AES       256
 x35     AES256-SHA                        RSA        AES       256
 xc013   ECDHE-RSA-AES128-SHA              ECDH 253   AES       128
 x2f     AES128-SHA                        RSA        AES       128
TLS 1.2
 xc030   ECDHE-RSA-AES256-GCM-SHA384       ECDH 253   AESGCM    256
 xcca8   ECDHE-RSA-CHACHA20-POLY1305       ECDH 253   CHACHA20  256
 xc028   ECDHE-RSA-AES256-SHA384           ECDH 253   AES       256
 xc014   ECDHE-RSA-AES256-SHA              ECDH 253   AES       256
 x9d     AES256-GCM-SHA384                 RSA        AESGCM    256
 x3d     AES256-SHA256                     RSA        AES       256
 x35     AES256-SHA                        RSA        AES       256
 xc02f   ECDHE-RSA-AES128-GCM-SHA256       ECDH 253   AESGCM    128
 xc027   ECDHE-RSA-AES128-SHA256           ECDH 253   AES       128
 xc013   ECDHE-RSA-AES128-SHA              ECDH 253   AES       128
 x9c     AES128-GCM-SHA256                 RSA        AESGCM    128
 x3c     AES128-SHA256                     RSA        AES       128
 x2f     AES128-SHA                        RSA        AES       128

 Done 2019-11-11 15:05:42`

After that we tested it with the radsecproxy module. It still doesn't work and says "no shared cipher". The client shows it supports the ciphers in the first post.
It seems like radsecproxy is not allowing to use ECDHE/DHE ciphers.
Is it somehow possible to activate them manually? I could not find anything like that in the config...

Why am I thinking it's a radsecproxy fault?
I tried to connect with another application, using the same server with the same openSSL version the radsecproxy is using. It works with DHE.

But no matter which setting I got, everytime there's this `tlsservernew: SSL accept from x.x.x.0/24 failed: error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher ` in the radsecproxy.log and this corresponding entry, when I take a tcpdump
![image](https://user-images.githubusercontent.com/57178434/68599485-ef0b6000-04a0-11ea-9137-debf1a99f86a.png)

**Comment by shartge** [comment]
If you capture the whole TLS negotiation you should be able to see what both sides are offering and which side is at fault here.

When doing so for my systems I can clearly see both sides advertising ECDHE and DHE ciphers in the Client-Hello-Phase.

**Comment by Jack1232323** [comment]
Hi,
thanks for the fast answer.

I've done a capture without any filter.
The whole communication looks like this:
![image](https://user-images.githubusercontent.com/57178434/68646451-81e8e080-051b-11ea-87f9-636c9a3a29fe.png)

When I take a look into the client hello, it shows all ECDHE and DHE ciphers:
![image](https://user-images.githubusercontent.com/57178434/68646535-c07e9b00-051b-11ea-9af4-bba01d2b4d36.png)

But the key negotiation fails, from the radsecproxy side:
![image](https://user-images.githubusercontent.com/57178434/68646575-dbe9a600-051b-11ea-81ae-21954dc0d4e2.png)

So it looks like the fault is on the server (radsecproxy) side....

**Comment by shartge** [comment]
No, it just seems like it.
radsecproxy does not limit or change the ciphers the SSL library uses, there is no code in radsecproxy that I can find that needs implementing.

I have shown that it will work with ECDHE and DHE ciphers if linked with an appropriate SSL library.

You should check which that is in the case of SLES and also check `/etc/ssl/openssl.cnf` for any system-wide policy preventing the use of those specific ciphers. The part you want to look at should be at the end, in the `[system_default_sect]`. I have set this to the following to allow all ciphers and protocols:

```
[system_default_sect]
MinProtocol = None
CipherString = DEFAULT
```

**Comment by Jack1232323** [comment]
Just tested with the newest openSSL library and your testtool, and I got the same result as you got:

```
 Testing ciphers per protocol via OpenSSL plus sockets against the server, ordered by encryption strength

Hexcode  Cipher Suite Name (OpenSSL)       KeyExch.   Encryption  Bits     Cipher Suite Name (IANA/RFC)
-----------------------------------------------------------------------------------------------------------------------------
SSLv2
SSLv3
 Oops: openssl s_client connect problem
TLS 1
 xc014   ECDHE-RSA-AES256-SHA              ECDH 253   AES         256      TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
 x35     AES256-SHA                        RSA        AES         256      TLS_RSA_WITH_AES_256_CBC_SHA
 xc013   ECDHE-RSA-AES128-SHA              ECDH 253   AES         128      TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
 x2f     AES128-SHA                        RSA        AES         128      TLS_RSA_WITH_AES_128_CBC_SHA
TLS 1.1
 xc014   ECDHE-RSA-AES256-SHA              ECDH 253   AES         256      TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
 x35     AES256-SHA                        RSA        AES         256      TLS_RSA_WITH_AES_256_CBC_SHA
 xc013   ECDHE-RSA-AES128-SHA              ECDH 253   AES         128      TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
 x2f     AES128-SHA                        RSA        AES         128      TLS_RSA_WITH_AES_128_CBC_SHA
TLS 1.2
 xc030   ECDHE-RSA-AES256-GCM-SHA384       ECDH 253   AESGCM      256      TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
 xc028   ECDHE-RSA-AES256-SHA384           ECDH 253   AES         256      TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
 xc014   ECDHE-RSA-AES256-SHA              ECDH 253   AES         256      TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
 xcca8   ECDHE-RSA-CHACHA20-POLY1305       ECDH 253   ChaCha20    256      TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
 x9d     AES256-GCM-SHA384                 RSA        AESGCM      256      TLS_RSA_WITH_AES_256_GCM_SHA384
 x3d     AES256-SHA256                     RSA        AES         256      TLS_RSA_WITH_AES_256_CBC_SHA256
 x35     AES256-SHA                        RSA        AES         256      TLS_RSA_WITH_AES_256_CBC_SHA
 xc02f   ECDHE-RSA-AES128-GCM-SHA256       ECDH 253   AESGCM      128      TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
 xc027   ECDHE-RSA-AES128-SHA256           ECDH 253   AES         128      TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
 xc013   ECDHE-RSA-AES128-SHA              ECDH 253   AES         128      TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
 x9c     AES128-GCM-SHA256                 RSA        AESGCM      128      TLS_RSA_WITH_AES_128_GCM_SHA256
 x3c     AES128-SHA256                     RSA        AES         128      TLS_RSA_WITH_AES_128_CBC_SHA256
 x2f     AES128-SHA                        RSA        AES         128      TLS_RSA_WITH_AES_128_CBC_SHA
TLS 1.3
 x1302   TLS_AES_256_GCM_SHA384            ECDH 253   AESGCM      256      TLS_AES_256_GCM_SHA384
 x1303   TLS_CHACHA20_POLY1305_SHA256      ECDH 253   ChaCha20    256      TLS_CHACHA20_POLY1305_SHA256
 x1301   TLS_AES_128_GCM_SHA256            ECDH 253   AESGCM      128      TLS_AES_128_GCM_SHA256

 Done 2019-11-12 09:51:17
```
So the openSSL and it's settings are fine.
But my client coming with the ciphers is still not working.
The Client Hello from my client looks also fine, so I really don't know where to look next...
Guess we have to go down to the old (good :D ) RADIUS without TLS....

**Comment by shartge** [comment]
I'm sorry, I can only pull the dreaded "works for me" card here.

But I am only just a user, for a real and final answer you should wait on input from @fmauchle

**Comment by Jack1232323** [comment]
I appreciate your help anyway, thanks :)

**Comment by fmauchle** [comment]
added config options for cipher-list/ciphersuite, tls version and dh-file.
