### ISSUE TITLE
Reestablish DTLS connection when not using status-server messages

### ISSUE THREAD

**Issue by jcsims** [radsecproxy/radsecproxy#61]
I'm using radsecproxy to proxy requests over a DTLS connection to a server that doesn't support status-server messages (ISE, in my case). Occasionally, the server will stop responding to any packets until the DTLS connection has been reestablished (either through a restart of radsecproxy, or a call to `dtlsconnect` in `dtlsclientrd`).

When I set `StatusServer off` in the config, radsecproxy doesn't seem to ever reestablish the DTLS connection, regardless of how many missing responses there are. I see this block would reestablish the DTLS connection if `server->conf->statusserver!=RSP_STATSRV_OFF`: https://github.com/radsecproxy/radsecproxy/blob/master/dtls.c#L660-L665, but is there some other method for radsecproxy to reestablish the connection of status-server messages are turned off?

I've tried:
- setting `StatusServer minimal` in config. This works in the sense that the connection is reestablished every 30 seconds or so. 
- a patch:
```patch
--- radsecproxy/dtls.c
+++ radsecproxy/dtls.c
@@ -646,8 +646,8 @@ void *dtlsclientrd(void *arg) {
 
     for (;;) {
     buf = raddtlsget(server->ssl, server->conf->retryinterval * (server->conf->retrycount+1), &server->lock);
-	if (!buf) {
-        if(SSL_get_shutdown(server->ssl) || (server->lostrqs && server->conf->statusserver!=RSP_STATSRV_OFF)) {
+    if (!buf) {
+        if(SSL_get_shutdown(server->ssl) || server->lostrqs ) {
             if (SSL_get_shutdown(server->ssl))
                 debug (DBG_WARN, "tlscleintrd: connection to server %s lost", server->conf->name);
             else if (server->lostrqs)

```
This patch seems to work in my limited local testing - is there a reason not to reestablish the connection when status-server is turned off?

**Comment by fmauchle** [comment]
The reason not to reestablish the connection is: if the server is itself a proxy, the loss of requests might be downstream, and you don't want to constantly reestablish the connection with the proxy when it is actually working fine.

But I'm not denying your use-case here. Using `StatusServer minimal`, even if not exactly meant to be used for this, is actually supposed to do what you want. It should only send a status-server if a normal request was lost (and no other requests received in that time), but be quiet if everything works fine or if there are no requests.

Just a wild guess: maybe the `RetryCount` causes the this; try setting it to `0`.

**Comment by fmauchle** [comment]
After some further digging, `RetryCount` won't make any difference.

However I think I found why the status-server is triggered every 30s here, which needs fixing.

**Comment by fmauchle** [comment]
The status-server issue is now fixed. With that, I think the `StatusServer minimal` is actually the way to go here.
