### ISSUE TITLE
Status Server Messages that are sent from Radius Client to the Radius Proxy are not sent to the  Radius Server

### ISSUE THREAD

**Issue by praneethgit** [radsecproxy/radsecproxy#69]
Hi,

Steps to reproduce.

1) Proxy and Radius server will have the TLS connection.
2) Now send the status server message from the Radius Client to Radsec Proxy.
3) Observe that the Status Messages will not get delivered to the Radius Server.
4) Proxy itself replies back to the Radius client.

Radius Authentication and Radius Accounting packets sent from the Radius client will get delivered to the radius server with TLS encrypted without any issues. 

Whenever I send the status message from Radius client , These status messages are not getting delivered to the Radius Server.

But the status messages directly sent from the proxy to the radius server will be delivered with TLS encrypted to the Radius Server, when I put "Status server messages on" in the configuration file.

Can you please check whether this is the expected behavior as the every message comes from the Radius client should be delivered to the radius server not just Authentication and accounting packets ?

**Comment by fmauchle** [comment]
Yes this is intentional as per [RFC5997](https://tools.ietf.org/html/rfc5997).

**Comment by praneethgit** [comment]
Thanks.
