### ISSUE TITLE
Compilation fails with -D_FORTIFY_SOURCE

### ISSUE THREAD

**Issue by benhur1999** [radsecproxy/radsecproxy#7]
When compiling with -D_FORTIFY_SOURCE, the build fails where asprintf is used and the return value is ignored. The first failure is:
```radsecproxy.c: In function ‘replylog’:
radsecproxy.c:1250:17: error: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Werror=unused-result]
         asprintf((char **)&tmp, " (%s)", replymsg);
```
Redhat/CentOS set -D_FORTIFY_SOURCE by default when building rpms using rpmbuild.

Environment:
- radsecproxy 1.7.1-rc1
- CentOS 7.4.1708
- GCC 4.8.5

Steps to reproduce:
`$ autoreconf -fi`
`$ env CPPFLAGS="-D_FORTIFY_SOURCE=1" CFLAGS="-O2" ./configure`
`$ make`

**Comment by hagedose** [comment]
I can confirm this, but I have an even earlier failure:

dtls.c: In Funktion »dtlslistener«:
dtls.c:412: Fehler: »ssl« may be used uninitialized in this function

When I disable DTLS, the error in radsecproxy.c is the first I encounter.

**Comment by fmauchle** [comment]
> dtls.c: In Funktion »dtlslistener«:
> dtls.c:412: Fehler: »ssl« may be used uninitialized in this function

This actually points to a more severe issue. Tracking as new issue #8 
It seems that only older versions of GCC will report this.
