### ISSUE TITLE
Malformed RADIUS packet from host

### ISSUE THREAD

**Issue by emileswarts** [radsecproxy/radsecproxy#79]
I have a FreeRadius server and radsecproxy set up and running locally in Docker containers, all the code for this can be found [here](https://github.com/emileswarts/freeradius-experiments).
I also have a test client with eapol_test installed. The authentication method is [EAP-TLS](https://github.com/emileswarts/freeradius-experiments/blob/main/test/eapol_test.conf).

When I run eapol_test against the server directly, the authentication succeeds. 
When I go through the radsecproxy, it fails to connect to the server:

`
server            |  ... new connection request on TCP socket
server            | Listening on auth from client (10.5.0.8, 44979) -> (*, 2083, virtual-server=default)
server            | Waking up in 0.7 seconds.
server            | Invalid packet from 10.5.0.8 port 44979, closing socket: Malformed RADIUS packet from host 10.5.0.8: attribute 168 data overflows the packet
server            | Client has closed connection
server            |  ... shutting down socket auth from client (10.5.0.8, 44979) -> (*, 2083, virtual-server=default)
server            | Ready to process requests

radsecproxy  |  SSL Connection failed: Connection reset by peer
radsecproxy  |  tlsconnect: SSL connect to 10.5.0.5 failed
radsecproxy  |  Next connection attempt to 10.5.0.5 in 60s
radsecproxy  |  tlsconnect: connecting to 10.5.0.5
radsecproxy  |  connecttcphostlist: trying to open TCP connection to 10.5.0.5 port 2083
radsecproxy  |  Connection up
radsecproxy  |  connecttcphostlist: TCP connection to 10.5.0.5 port 2083 up
radsecproxy  |  SSL Connection failed: Connection reset by peer
radsecproxy  |  tlsconnect: SSL connect to 10.5.0.5 failed
radsecproxy  |  Next connection attempt to 10.5.0.5 in 60s
`

There are two errors here that I'm trying to find out if they are related:
1. SSL Connection failed
2. Malformed RADIUS packet

My radsecproxy configuration file can be found here:
https://github.com/emileswarts/freeradius-experiments/blob/main/radsecproxy/radsecproxy.conf

I've run a packet capture to see what is happening but cannot get any descriptive error messages. I can see a TCP reset being sent to the proxy from the server though:

`
6	0.008377500	10.5.0.5	10.5.0.8	TCP	66	2083 → 41591 [RST, ACK] Seq=1 Ack=294 Win=64896 Len=0 TSval=1816285834 TSecr=554832364
`

If anyone has any ideas how to debug this further, please let me know.

Thanks,
Emile

**Comment by fmauchle** [comment]
It has been some time since I last did radsec on FreeRadius. I guess your FreeRadius is not expecting a TLS connection, but plain TCP.
- Either tell radsecproxy to use plain TCP `type TCP`
- Or enable TLS on the FreeRadius side. According to the examples, the `listen` section will need a `tls` subsection:
```
listen {
  proto = tcp
  tls {
    ca_file = ${cadir}/ca.pem
    ...
  }
}
```

**Comment by emileswarts** [comment]
Yes! that was indeed the issue, thanks for pointing me in the right direction. 
For anyone interested in the fix, see this repo: https://github.com/emileswarts/freeradius-experiments
