### ISSUE TITLE
SNI support (feature request)

### ISSUE THREAD

**Issue by Tarick** [radsecproxy/radsecproxy#88]
Is it possible to add Server Name Identification support? I have the need to host multiple RADIUS servers behind single load balancer and would like to route requests based on DNS name in TLS ClientHello message with SNI.

**Comment by jerryz1982** [comment]
same here

**Comment by alandekok** [comment]
FYI, I've just added this to FreeRADIUS.  Both for incoming and outgoing packets.  See https://github.com/FreeRADIUS/freeradius-server/tree/v3.0.x/raddb/certs/realms#readme

Client connections can set the SNI.  Servers receiving client connections can dynamically choose their certificates, based on SNI.

This will be in 3.0.24.
